import { Article } from './article';

export const ARTICLES: Article[] = [
    new Article('Geschiedenis van Leiden', `De stad ontstond als dijkdorp aan de zuidzijde tegenover een kunstmatige heuvel aan de samenvloeiing van de Oude en de Nieuwe Rijn. In de oudste vermelding daarvan, omstreeks 860, werd het toenmalige dorp Leithon genoemd. In de op deze heuvel gelegen burcht zetelde aanvankelijk een leenman van de bisschop van Utrecht, maar de burcht kwam omstreeks 1100 in handen van de graaf van Holland. De gunstig gelegen nederzetting kreeg in 1266 bevestiging van de reeds eerder verleende stadsrechten en ontwikkelde zich met haar bloeiende lakennijverheid tot een van de grootste steden van het gewest Holland. In 1389, toen de bevolking tot ongeveer 4.000 was gegroeid, moest de stad worden uitgebreid met het stadsdeel tussen Rapenburg (tevoren de zuidrand van de stad) en de Witte Singel.
    In 1420 werd Leiden, in het kader van de Hoekse en Kabeljauwse twisten veroverd door hertog Jan VI van Beieren. Op 1 maart 1512 stortte de ruim 100 meter hoge toren van de Pieterskerk bij een storm in. De toren, een van de hoogste van Nederland, werd nimmer herbouwd.
    In 1572 koos de stad de zijde van de anti-Spaanse opstand. De Spaanse landvoogd Requesens belegerde in 1574 de stad. Nadat dit beleg was afgeslagen - Leidens ontzet van 3 oktober 1574 - kreeg de stad in 1575 met de Universiteit Leiden de eerste universiteit van Nederland. De in vele bronnen gegeven verklaring dat stadhouder Willem van Oranje hiermee zijn erkentelijkheid aan de Leidenaren betuigde is enigszins twijfelachtig. Willem had namelijk een politiek/bestuurlijke reden voor de oprichting van een universiteit: de behoefte aan goed opgeleide getrouwen. De universiteit voert als motto Praesidium Libertatis, dat 'bolwerk van de vrijheid' betekent.
    In de 17e eeuw kwam de stad tot grote bloei, dankzij de impuls die vluchtelingen uit Vlaanderen gaven aan de textielnijverheid. De stad, die voor het beleg van 1574 ongeveer 15.000 inwoners had geteld, waarvan tijdens het beleg ongeveer een derde deel het leven had verloren, was in 1622 tot 45.000 inwoners gegroeid en omstreeks 1670 werd zelfs een aantal van tegen de 70.000 bereikt. In de Gouden Eeuw was Leiden, na Amsterdam, de op één na grootste stad van Nederland. De bevolkingsgroei maakte een aanleg van nieuwe grachten en singels noodzakelijk. Het huidige centrum van Leiden, herkenbaar aan het singelpatroon, werd in 1659 voltooid.
    In de 18e eeuw raakte de textielnijverheid in verval, door protectionistische maatregelen in Frankrijk en de lonen, die vanwege de kosten van levensonderhoud in het gewest Holland relatief hoog moesten zijn. Het gevolg was een gestadige daling van het inwonertal van Leiden, dat eind 18e eeuw tot 30.000 was gedaald en omstreeks 1815 een dieptepunt van 27.000 zou bereiken.
    Op 12 januari 1807 vond de Leidse buskruitramp plaats, waarbij ongeveer 150 burgers om het leven kwamen. Koning Lodewijk Napoleon bezocht persoonlijk de stad om de hulp aan de slachtoffers te coördineren. Op de plaats van de door de ontploffing veroorzaakte "ruïne" werden later het Van der Werfpark en het Kamerlingh Onnes Laboratorium aangelegd. In 1842 werd de voor Leiden zeer belangrijke spoorlijn naar Haarlem in gebruik genomen. In 1866 werd de stad getroffen door de laatste grote epidemie (cholera) die in 1868 leidde tot de start van de bouw van het nieuw Academisch Ziekenhuis. In 1883 werd niet alleen Leiden, maar ook de rest van Nederland, opgeschrikt door het nieuws van de arrestatie van de Maria Swanenburg, bijgenaamd Goeie Mie, een gifmengster die in enkele jaren tijd minstens 27 slachtoffers had gemaakt. Mede dankzij de spoorlijn was in de 19e eeuw enige verbetering opgetreden in de desolate sociaal-economische situatie, maar het aantal inwoners was omstreeks 1900 nog steeds niet ver boven de 50.000 opgeklommen. Pas in 1896 begon Leiden zich uit te breiden buiten de 17e-eeuwse singels.
    Tijdens de Tweede Wereldoorlog werd Leiden zwaar getroffen door geallieerde bombardementen. De omgeving van het station en de Marewijk (tegenwoordig de omgeving van het Schuttersveld en de Schipholweg) werden vrijwel geheel met de grond gelijk gemaakt. Het historische centrum is gespaard gebleven.
    Het huidige Leiden profileert zich vooral als een centrum van wetenschappelijke kennis en nieuwe technologie. Daarnaast speelt ook het toerisme een steeds belangrijkere rol in deze historische vestingstad.
    Leiden heeft een eigen canon.[11] De Leidse Canon vertelt de geschiedenis van Leiden aan de hand van 35 belangrijke historische onderwerpen. `),
    new Article("Levensloop Gerard 't Hooft", `’t Hooft is lid van de familie 't Hooft en werd geboren als tweede van drie kinderen en bracht zijn jeugd door in Den Haag. Zijn vader was maritiem ingenieur, zijn moeder kwam uit een geslacht van natuurkundigen. Zo was zijn oudoom Nobelprijswinnaar Frits Zernike, de uitvinder van de fasecontrastmicroscoop. Zijn oom Nico van Kampen, hoogleraar in Utrecht, zette hem op het pad van de natuurkunde en begeleidde hem in het begin van zijn carrière. Na het gymnasium (Dalton Den Haag) studeerde 't Hooft wis- en natuurkunde aan de Universiteit Utrecht en promoveerde daar in 1972. Al voor de promotie publiceerde hij met zijn promotor Martin Veltman baanbrekende artikelen over deeltjesfysica, waardoor hij in één klap binnen het vakgebied beroemd werd.

    Ondanks aanbiedingen is ’t Hooft niet naar een Amerikaanse universiteit vertrokken. Zijn band met Nederland heeft hem in Utrecht gehouden. Hij werd tijdens zijn studie lid van het Utrechtsch Studenten Corps en ging roeien bij Triton. Sinds 1977 is hij er hoogleraar theoretische natuurkunde, verbonden aan het Spinoza-instituut[1] sinds de oprichting in 1998. Hij heeft er op zijn beurt een aantal talenten opgeleid. Zo promoveerden Herman Verlinde, Erik Verlinde en Robbert Dijkgraaf bij hem.
    
    Prijzen en lidmaatschappen
    Als scholier was Gerard ’t Hooft al een getalenteerd wetenschapper. In de vijfde klas van de middelbare school won hij een tweede prijs op de Nederlandse Wiskunde Olympiade.
    
    In 1999 kreeg hij met Martinus Veltman de Nobelprijs voor de Natuurkunde voor het ophelderen van de kwantumstructuur van elektrozwakke interacties in de natuurkunde. Veltman is in 1981 vanwege onenigheid, die erover ging wie de eer van hun ontdekkingen toekwam, uit Utrecht vertrokken, maar nadat hun beide de Nobelprijs was toegekend, hebben zij hun geschil bijgelegd.
    ’t Hooft besteedt sinds 1999 veel tijd aan lezingen in binnen- en buitenland. Eerder ontving hij ook al velerlei eerbewijzen, zoals de Israëlische Wolfprijs voor de natuurkunde van 1981, samen met Freeman Dyson en Victor Weisskopf, de Franklin Medal uit de VS, de Spinozapremie en een aantal eredoctoraten. De planetoïde 9491 Thooft is naar hem genoemd,[2] Hij is sinds 1982 lid van de Koninklijke Nederlandse Akademie van Wetenschappen, die hem in 2003 tot Akademiehoogleraar benoemde en hem in 1986 de Lorentzmedaille toekende. Tevens is hij (buiten)lid van de wetenschapsacademies van België, Frankrijk en de Verenigde Staten. ’t Hooft is Commandeur in de Orde van de Nederlandse Leeuw en Officier in het Franse Legioen van Eer.
    
    Persoonlijk
    ’t Hooft is getrouwd met Albertha Anje Schik (Betteke) en heeft twee dochters. Zijn Nederlandse boek Planetenbiljart is door zijn dochter Saskia Eisberg-’t Hooft naar het Engels vertaald en verscheen in 2008 met als titel Playing with Planets.  `),
    new Article('Overzicht Kwantummechanica', `In de kwantumtheorie wordt de werkelijkheid op een fundamenteel andere manier benaderd dan in de klassieke natuurkunde, waarin ervan wordt uitgegaan dat er een waarnemeronafhankelijke werkelijkheid is en natuurkundige grootheden continue variabelen zijn, die in elke gewenste combinatie gemeten kunnen worden. Meetonnauwkeurigheden worden in de klassieke natuurkunde gezien als een praktisch probleem.

    In de kwantumtheorie (althans in de breed aangehangen Kopenhaagse interpretatie van Niels Bohr en Werner Heisenberg) variëren natuurkundige grootheden stapsgewijs (met 1 kwantum tegelijk) en kan er geen enkele waarneming worden gedaan zonder dat het waargenomen verschijnsel wordt beïnvloed. Er is in de kwantumtheorie dus geen waarnemeronafhankelijke werkelijkheid. Door dit tweede fundamentele verschil met de klassieke natuurkunde is het principieel uitgesloten om het effect van de waarneming uit te schakelen: de keuze die de waarnemer maakt bij het opzetten van een experiment bepaalt in belangrijke mate de uitkomst daarvan. Het product van de onnauwkeurigheden van de gelijktijdige metingen van twee grootheden (bijvoorbeeld plaats en impuls) heeft volgens de onzekerheidsrelatie van Heisenberg een minimale waarde. Is de ene grootheid met de grootst mogelijke nauwkeurigheid gemeten, dan is de andere onvermijdelijk geheel onbepaald en ook niet bepaalbaar. De onzekerheidsrelatie is zelf echter wel nauwkeurig en objectief geformuleerd. Op macroscopische schaal is de invloed van kwantummechanische beperkingen op de nauwkeurigheid meestal verwaarloosbaar of geheel niet meetbaar en gaat de kwantummechanica over in de klassieke natuurkunde: dat heet het correspondentieprincipe.
    
    De kwantummechanica doet bovendien slechts statistische uitspraken over een reeks van waarnemingen. Dat heeft tot gevolg dat het gedrag van een individueel elementair deeltje slechts in termen van waarschijnlijkheid kan worden beschreven. Die waarschijnlijkheden worden beschreven door de modulus in het kwadraat van de complexe golffuncties, die de kansdichtheid geven op het meten van een bepaalde waarde van een fysische grootheid zoals bv. plaats, snelheid en spin. Met de term "spin" wordt de kwantummechanische versie van het impulsmoment genoemd.
    
    De beschrijving van systemen door middel van een golffunctie betekent dat deeltjes zich, afhankelijk van de manier waarop ze worden waargenomen, soms als een deeltje in klassieke zin, maar soms als een golfverschijnsel gedragen. Zo kunnen bijvoorbeeld elektronenbundels, net als lichtbundels, brekingsverschijnselen en interferentie en diffractie vertonen. Andersom kan licht ook beschouwd worden als bestaande uit kwanta, die in het geval van licht fotonen genoemd worden, met een energie E:
    
        E = h ν {\displaystyle E=h\nu } {\displaystyle E=h\nu }
    
    waarin h {\displaystyle h} h de constante van Planck en ν {\displaystyle \nu } \nu (de Griekse letter nu) de frequentie van het licht.
    
    Bij het formuleren van de kwantummechanica in termen van golffuncties blijkt dat bepaalde fysische grootheden uitsluitend waarden kunnen aannemen uit een bepaalde verzameling, die van de situatie en de te meten grootheid afhangt. Een bekend voorbeeld is het feit dat elektronen in een atoom slechts bepaalde energieniveaus kunnen bezetten, wat aanleiding geeft tot spectraallijnen in het licht dat door het atoom wordt uitgezonden. Een ander opmerkelijk feit in de kwantummechanica is dat fysische grootheden van een systeem in sommige combinaties niet tegelijkertijd met willekeurige nauwkeurigheid bekend kunnen zijn. De belangrijkste voorbeelden hiervan zijn plaats x en impuls p, en tijd t en energie E. Dit feit staat bekend als de onzekerheidsrelatie van Heisenberg. De onnauwkeurigheden Δ in deze grootheden zijn naar onder in grootte begrensd door de volgende ongelijkheden:
    
        Δ x Δ p ≥ h 4 π {\displaystyle \Delta x\Delta p\geq {\frac {h}{4\pi }}} \Delta x\Delta p\ge \frac h{4\pi}
        Δ E Δ t ≥ h 4 π {\displaystyle \Delta E\Delta t\geq {\frac {h}{4\pi }}} \Delta E\Delta t\geq {\frac h{4\pi }}
    
    Dit volgt rechtstreeks uit de aanname van golfeigenschappen en uit de wiskundige eigenschap van de fouriertransformatie. Er zijn nog tal van andere onzekerheidsrelaties tussen paren van fysische grootheden, die daarom niet-commuterend worden genoemd. In jargon zegt men dat bij meten (waarnemen) van een willekeurige variabele de golffunctie wordt geprojecteerd op een eigentoestand. Dit betekent dat alle andere informatie (over alle andere observabelen) verloren gaat. De onzekerheidsrelatie tussen twee willekeurige niet-commuterende grootheden wordt gegeven door:
    
        Δ A Δ B ≥ 1 2 | ⟨ [ A , B ] ⟩ | {\displaystyle \Delta A\,\Delta B\geq {\tfrac {1}{2}}|\langle [{A},{B}]\rangle |} {\displaystyle \Delta A\,\Delta B\geq {\tfrac {1}{2}}|\langle [{A},{B}]\rangle |}
    
    De kwantummechanica maakt onderscheid tussen twee typen deeltjes : bosonen en fermionen. Het onderscheid zit in de spin van het deeltje, een fundamentele eigenschap die alleen van het type deeltje afhangt en de waarden 0 , 1 2 , 1 , 3 2 , … {\displaystyle 0,{\tfrac {1}{2}},1,{\tfrac {3}{2}},\ldots } {\displaystyle 0,{\tfrac {1}{2}},1,{\tfrac {3}{2}},\ldots } kan aannemen. De deeltjes met heeltallige spin heten bosonen, de andere worden fermionen genoemd. Een belangrijk resultaat met betrekking tot dit onderscheid is het uitsluitingsprincipe van Pauli, dat zegt dat er geen twee fermionen naast elkaar in dezelfde toestand kunnen bestaan. Voor de bosonen is dat wel mogelijk. `),
    new Article('Levensloop Leonhard Euler', `Jonge jaren in Zwitserland - 1707-1727

    Euler werd in Bazel geboren als zoon van de hervormde predikant Paul Euler en zijn vrouw Margarete Brucker, zelf ook de dochter van een predikant. Hij had twee jongere zusters, Anna Maria en Maria Magdalena. Kort na de geboorte van Leonhard verhuisde het gezin van Bazel naar het nabijgelegen stadje Riehen, waar Euler het grootste deel van zijn kindertijd doorbracht. Paul Euler was een vriend van de familie Bernoulli, met name Johann Bernoulli, die toen werd beschouwd als de belangrijkste wiskundige van Europa en de man die uiteindelijk de belangrijkste invloed op de jonge Leonhard zou hebben. Eulers eerste stappen in het onderwijs vonden plaats in Bazel, waar hij bij zijn grootmoeder van moederskant ging inwonen. Hij bezocht de Latijnse school, waar toen nog geen wiskundeonderwijs werd gegeven. Op de leeftijd van dertien jaar schreef hij zich in 1720 in aan de faculteit filosofie van de Universiteit van Bazel. Het curriculum van deze universiteit was in die tijd nog vrij beperkt en reeds twee jaar later, in 1722, studeerde Euler op vijftienjarige leeftijd af in de filosofie.
    
    Op aandrang van zijn vader schreef hij zich nu in aan de theologische faculteit, waar hij naast de theologische vakken ook Grieks en Hebreeuws leerde. Zijn vader wilde dat Leonhard net als hij zelf ook predikant zou worden. Na aan hem voorgesteld te zijn had Johann Bernoulli geweigerd om Euler onderwijs in de wiskunde te geven, wel stond Johann Bernoulli hem toe om hem elke zaterdagmiddag thuis te bezoeken om vragen te stellen of om uitleg te vragen op die onderdelen waar Euler bij zijn zelfstudie wiskunde was vastgelopen. Bernoulli ontdekte het uitzonderlijke talent van Leonhard Euler voor de wiskunde al snel.[2] In 1724, hij was nu zeventien, behaalde Euler zijn doctoraal theologie met een scriptie, waarin hij de filosofieën van Descartes en Newton met elkaar vergeleek. Uiteindelijk overtuigde Johann Bernoulli Paul Euler ervan dat zijn zoon Leonhard voorbestemd was om een groot wiskundige te worden. In 1726 studeerde Euler voor de derde keer af, nu met een proefschrift over de voortplantingssnelheid van geluid met de titel De Sono.[3]
    
    Hij deed in 1727 voor het eerst mee aan de door de Académie des sciences in Parijs periodiek uitgeschreven wiskundewedstrijd. De opdracht was om de beste plaats te bepalen, waar op een schip de mast moet worden geplaatst. Euler won de tweede plaats, achter Pierre Bouguer, de "vader van de marine-architectuur". In totaal zou Euler deze begeerde jaarlijkse prijs twaalf keer winnen.[4]
    Sint-Petersburg - 1727–1741
    
    Rond deze tijd waren twee zonen van Johann Bernoulli, Daniel en Nicolaas, werkzaam aan de Russische Academie van Wetenschappen in Sint-Petersburg. Na een jaar in Rusland te hebben doorgebracht overleed Nicolaas in juli 1726 aan de gevolgen van een blindedarmontsteking. Zijn broer Daniel nam zijn taken op het gebied van de wis- en natuurkunde over, maar hij adviseerde om zijn vriend Leonhard Euler de taken van zijn broer op het gebied van de fysiologie over te laten nemen. In november 1726 ging Euler op dit aanbod in. Hij had al in 1726, meteen na zijn promotie, naar Sint-Petersburg kunnen vertrekken, maar hij vertrok pas in het volgende voorjaar, omdat hij zijn reis naar Sint-Petersburg uitstelde tot hij zeker was niet in aanmerking te komen voor een hoogleraarschap natuurkunde aan de universiteit van Bazel.[4]
    
    Op 17 mei 1727 arriveerde Euler, net twintig jaar oud, in de Russische hoofdstad. Al snel werd hij van zijn juniorfunctie binnen de medische afdeling van de academie gepromoveerd naar een positie binnen de wiskunde-afdeling. Hij werkte nauw samen met Daniël Bernoulli bij wie hij de eerste tijd ook in huis woonde. Euler leerde Russisch en paste zich snel aan het leven in Sint-Petersburg aan. Ook nam hij een extra baan als medisch adviseur voor de Russische Marine aan.[4]
    
    De Academie van Sint-Petersburg, in 1724 opgericht door Peter de Grote, had tot doel om het onderwijs in Rusland op een hoger plan te brengen en om de wetenschappelijke kloof met West-Europa te overbruggen. Omdat de academie kon beschikken over ruime financiële middelen en een uitgebreide bibliotheek, samengesteld uit privé-bibliotheken van Peter de Grote en andere adellijke personen, was de academie zeer aantrekkelijk voor buitenlandse wetenschappers zoals Euler. Er stonden slechts weinig leerlingen aan de academie ingeschreven, waardoor de leden van de academie een lichte onderwijstaak hadden. Mede daarom bleef er genoeg tijd over om fundamenteel wetenschappelijk onderzoek te doen.[4]
    
    Precies op de dag van Eulers aankomst in mei 1727 in Sint-Petersburg overleed de beschermvrouwe van de Academie, Catherina I. Zij had vastgehouden aan het progressieve beleid van haar ruim twee jaar eerder overleden echtgenoot. Na haar dood nam de macht van de nog grotendeels conservatieve Russische adel, die als regent optrad voor de twaalfjarige Peter II, sterk toe. Deze adel vond de buitenlandse geleerden van de academie maar verdacht. De beschikbare gelden werden sterk verminderd. Ook op andere manieren maakte men de academieleden het leven zuur.
    
    Na de dood van Peter II in 1730 verbeterde de situatie iets. In deze periode steeg Eulers ster snel en reeds in 1731 werd hij tot hoogleraar in de natuurkunde benoemd. Twee jaar later had zijn vriend Daniël Bernoulli genoeg van de censuur en de vijandigheid die hij in Sint-Petersburg moest verdragen en hij keerde terug naar Bazel. Euler volgde hem op als het hoofd van afdeling wiskunde.[5]
    
    Op 7 januari 1734 trad Leonhard in het huwelijk met Katharina Gsell, de dochter van de Zwitserse barokschilder, Georg Gsell, die door Peter de Grote naar Rusland was gehaald en die in Sint-Petersburg aan het Academiegymnasium werkzaam was. Het jonge paar kocht een huis aan de rivier Neva. Zij kregen dertien kinderen, van wie er echter slechts vijf de jeugd overleefden.[6]
    
    Vanaf 1735 begon Eulers gezondheid hem parten te spelen. Dat jaar bezweek hij bijna aan de koorts. Ook werd hij bijna blind aan zijn rechteroog, waarschijnlijk als gevolg van scrofulose. Dit kon door een chirurgische ingreep tijdelijk worden verholpen. Als oorzaak van dit probleem zag Euler zelf het voor zijn ogen vermoeiende cartografische werk dat hij toen voor de Academie van Sint-Petersburg uitvoerde om een kaart van Rusland samen te stellen.
    Berlijn - 1741–1766
    
    Bezorgd over de hernieuwde politieke onrust in Rusland, waar de regente Anna Leopoldovna aan de kant was geschoven door de nieuwe tsarina Elisabeth van Rusland, verliet Euler op 19 juni 1741 Sint-Petersburg om op uitnodiging van Frederik de Grote een benoeming aan de Berlijnse Academie te aanvaarden. De daaropvolgende vijfentwintig jaar leefde hij in Berlijn, waar hij meer dan 380 artikelen schreef. In Berlijn publiceerde hij de twee werken waar hij zijn grootste bekendheid aan zou ontlenen: de Introductio in analysin infinitorum, een tekst over functies, die hij in 1748 publiceerde, en de Institutiones Calculi differentialis[7], een boek over differentiaalrekening, dat in 1755 werd gepubliceerd.[8]
    
    Euler werd gevraagd om privéleraar te worden van Frederiks nichtje, de prinses van Anhalt-Dessau. Hij schreef haar meer dan 200 brieven, die later werden verzameld in een goedverkopend brievenboek met de titel Brieven van Euler gericht aan een Duitse prinses over verschillende onderwerpen in de natuurlijke filosofie. Dit werk bevatte Eulers uitleg over diverse natuurkundige en wiskundige onderwerpen en gaf ook waardevolle inzichten in Eulers persoonlijkheid en religieuze overtuigingen. Dit boek bereikte een veel groter publiek dan enige van zijn wetenschappelijke wiskundige werken. Het werd in heel Europa en later ook in de Verenigde Staten uitgegeven. De populariteit van dit 'brievenboek' getuigt van Eulers vermogen om wetenschappelijke vraagstukken doeltreffend aan een lekenpubliek uit te leggen [8] en daarom kan Euler als een van de eerste wetenschapspopularisators worden beschouwd.
    
    Ondanks zijn immense bijdrage aan het prestige van de Berlijnse Academie werd Euler uiteindelijk toch gedwongen Berlijn te verlaten. Dit was deels te wijten aan een persoonlijke botsing met Frederik. Deze ontstond toen Euler na het vertrek van de voorzitter van de Berlijnse Academie, Pierre-Louis de Maupertuis, in 1756 steeds meer de rol van waarnemend voorzitter van de Berlijnse academie op zich moest nemen. Frederik de Grote had geen vertrouwen in Euler, die hij steeds meer als te weinig verfijnd beschouwde, zeker in vergelijking met de kring van filosofen die de Pruisische koning in zijn Academie had verzameld, onder wie Voltaire die een prominente positie aan het hof van de koning genoot. Euler, een orthodox calvinist en een harde werker, was zeer conventioneel in zijn overtuigingen en smaak. Hij was in veel opzichten de directe tegenpool van Voltaire. Euler had slechts een beperkte opleiding in de retorica genoten en had de neiging te discussiëren over zaken waar hij weinig van wist, daarmee de spot van Voltaire over zich afroepend. Ook op de praktische ingenieurskwaliteiten van Euler viel het een en ander aan te merken. Frederik de Grote uitte zich in een brief aan Voltaire hierover zeer teleurgesteld:[8]
    Aanhalingsteken openen 	
    
    Ik wou een fontein in mijn tuin hebben: Euler berekende de benodigde kracht van de waterwielen om het water uit het reservoir op te tillen, door pijpen te laten lopen en in Sanssouci uit de fontein te laten spuiten. Mijn watermolen werd meetkundig uitgevoerd maar bleek op een afstand van minder van vijftig passen niet in staat om een handjevol water te verplaatsen. IJdelheid der ijdelheden! IJdelheid van de meetkunde![9]
        Aanhalingsteken sluiten
    
    Toen Frederik de Grote ten slotte Euler passeerde en het voorzitterschap tevergeefs aanbood aan Jean le Rond d'Alembert, keerde Euler, die zich dan ook gepasseerd voelde, terug naar Sint-Petersburg. Gedurende het eind van zijn verblijf in Pruisen verslechterde langzamerhand ook Eulers gezichtsvermogen aan zijn rechteroog. Frederik de Grote was zo onbeleefd om aan Euler als een “cycloop” te refereren.
    Sint-Petersburg - 1766–1783
    
    Sinds de troonsbestijging in 1762 van Catharina de Grote, een van oorsprong Noord-Duitse prinses met meer sympathie voor de ideeën van de Verlichting dan de conservatieve Russische adel, was de situatie in Rusland sterk verbeterd en in 1766 aanvaardde Euler een uitnodiging om terug te keren naar de Academie van Sint-Petersburg, Daar bracht hij de resterende zeventien jaar van zijn leven door. Zijn tweede verblijf in het land werd echter getekend door tragedie. In 1766 ontwikkelde Euler in zijn nog goede linkeroog grijze staar. In die tijd kon daar niets aan gedaan worden en binnen een paar weken was Euler, mede als gevolg van een mislukte operatie, volkomen blind. Vijf jaar later, in 1771 brandde zijn huis af. Hij kon ternauwernood ontsnappen. Tot overmaat van ramp overleed in 1773, na een huwelijk van bijna veertig jaar, zijn vrouw Katharina Gsell. Drie jaar later hertrouwde Euler met haar halfzus, Salome Abigail Gsell. Dit huwelijk zou tot aan zijn dood blijven duren.
    Tombe van Leonhard Euler in het Alexander Nevski-klooster.
    
    Zijn blindheid had wonderlijk genoeg weinig effect op zijn productiviteit. Hij kon deze handicap compenseren door zijn vaardigheden om in zijn hoofd ingewikkelde berekeningen uit te voeren. Bovendien kon hij een beroep doen op zijn fotografisch geheugen. Euler was bijvoorbeeld in staat de Aeneis van Vergilius van het begin tot het einde te reciteren. Met steun van familieleden, met name zijn oudste zoon, de wiskundige Johann Euler, die precies opschreven wat hij hun dicteerde, slaagde Euler er volgens sommigen in zijn productiviteit nog te verhogen. In het jaar 1775 produceerde hij gemiddeld één wiskundig artikel per week.[10]
    
    Op 18 september 1783 overleed Euler in Sint-Petersburg op 76-jarige leeftijd aan de gevolgen van een hersenbloeding. Hij werd naast zijn eerste vrouw begraven op de Smolensk Lutherse Begraafplaats op Vasilevski-eiland. Later werd deze begraafplaats door de Sovjet-autoriteiten geruimd, overigens wel nadat zij het gebeente van Euler hadden laten overbrengen naar het orthodoxe Alexander Nevski-klooster. Zijn grafrede voor de Franse Académie des sciences werd geschreven door de Franse wiskundige en filosoof markies Nicolas de Condorcet. Die merkte op:
    Aanhalingsteken openen 	
    
    …il cessa de calculer et de vivre – … Hij stopte met rekenen en leven.[11]
        Aanhalingsteken sluiten
    
    Een overzicht van zijn leven, inclusief een lijst van zijn werken, werd opgesteld door Eulers schoonzoon Nikolaus von Fuss, die secretaris was van de Keizerlijke Academie van Sint-Petersburg. `),
    new Article('Artikel Vijf', `Lœrem ipsum dœlœr sit amet, cœnsectetuer adipiscing elit. Aenean cœmmœdœ ligula eget dœlœr. Aenean massa. Cum sœciis natœque penatibus et magnis dis parturient mœntes, nascetur ridiculus mus. Dœnec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla cœnsequat massa quis enim. Dœnec pede justœ, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justœ, rhœncus ut, imperdiet a, venenatis vitae, justœ. Nullam dictum felis eu pede mœllis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leœ ligula, pœrttitœr eu, cœnsequat vitae, eleifend ac, enim. Aliquam lœrem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laœreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcœrper ultricies nisi. Nam eget dui. `),
]