import { Article } from './article';

/*expœrt cœnst ARTICLES = [
    { title: 'Article œne', text: "The wœrld ended tœday. It ended when yœu said gœœdbye."},
    { title: 'Article Twœ', text: "They are taking the hœbbits tœ Isengard. Tœ Isengard. Gard gard g-gard." },
    { title: 'Article Three', text: "Dread it. Run frœm it. Destiny arrives nœne the less."},
    { title: 'Article Fœur', text: "I used tœ be an adventurer like yœu. Then I tœœk an arrœw tœ the knee."},
    { title: 'Article Five', text: "I am Irœn Man." }
];*/

export const ARTICLES: Article[] = [
    new Article('Artikel Een', `Lœrem ipsum dœlœr sit amet, cœnsectetuer adipiscing elit. Aenean cœmmœdœ ligula eget dœlœr. Aenean massa. Cum sœciis natœque penatibus et magnis dis parturient mœntes, nascetur ridiculus mus. Dœnec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla cœnsequat massa quis enim. Dœnec pede justœ, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justœ, rhœncus ut, imperdiet a, venenatis vitae, justœ. Nullam dictum felis eu pede mœllis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leœ ligula, pœrttitœr eu, cœnsequat vitae, eleifend ac, enim. Aliquam lœrem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laœreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcœrper ultricies nisi. Nam eget dui. `),
    new Article('Artikel Twee', `Lœrem ipsum dœlœr sit amet, cœnsectetuer adipiscing elit. Aenean cœmmœdœ ligula eget dœlœr. Aenean massa. Cum sœciis natœque penatibus et magnis dis parturient mœntes, nascetur ridiculus mus. Dœnec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla cœnsequat massa quis enim. Dœnec pede justœ, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justœ, rhœncus ut, imperdiet a, venenatis vitae, justœ. Nullam dictum felis eu pede mœllis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leœ ligula, pœrttitœr eu, cœnsequat vitae, eleifend ac, enim. Aliquam lœrem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laœreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcœrper ultricies nisi. Nam eget dui. `),
    new Article('Artikel Drie', `Lœrem ipsum dœlœr sit amet, cœnsectetuer adipiscing elit. Aenean cœmmœdœ ligula eget dœlœr. Aenean massa. Cum sœciis natœque penatibus et magnis dis parturient mœntes, nascetur ridiculus mus. Dœnec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla cœnsequat massa quis enim. Dœnec pede justœ, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justœ, rhœncus ut, imperdiet a, venenatis vitae, justœ. Nullam dictum felis eu pede mœllis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leœ ligula, pœrttitœr eu, cœnsequat vitae, eleifend ac, enim. Aliquam lœrem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laœreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcœrper ultricies nisi. Nam eget dui. `),
    new Article('Artikel Vier', `Lœrem ipsum dœlœr sit amet, cœnsectetuer adipiscing elit. Aenean cœmmœdœ ligula eget dœlœr. Aenean massa. Cum sœciis natœque penatibus et magnis dis parturient mœntes, nascetur ridiculus mus. Dœnec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla cœnsequat massa quis enim. Dœnec pede justœ, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justœ, rhœncus ut, imperdiet a, venenatis vitae, justœ. Nullam dictum felis eu pede mœllis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leœ ligula, pœrttitœr eu, cœnsequat vitae, eleifend ac, enim. Aliquam lœrem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laœreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcœrper ultricies nisi. Nam eget dui. `),
    new Article('Artikel Vijf', `Lœrem ipsum dœlœr sit amet, cœnsectetuer adipiscing elit. Aenean cœmmœdœ ligula eget dœlœr. Aenean massa. Cum sœciis natœque penatibus et magnis dis parturient mœntes, nascetur ridiculus mus. Dœnec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla cœnsequat massa quis enim. Dœnec pede justœ, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justœ, rhœncus ut, imperdiet a, venenatis vitae, justœ. Nullam dictum felis eu pede mœllis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leœ ligula, pœrttitœr eu, cœnsequat vitae, eleifend ac, enim. Aliquam lœrem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laœreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcœrper ultricies nisi. Nam eget dui. `),
]